adding coding

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -23,24 +23,24 @@ jobs :
     container:
       image: ghcr.io/epitech/coding-style-checker:latest
     steps :
-        uses : actions/checkout@v4
-        - run : check.sh $(pwd) $(pwd)
-        - run : |
-          if [ -s "coding-style-reports.log" ]; then
-            filename="coding-style-reports.log"
-            count=0
-            while read -r line; do
-              ((count+=1))
-            done <$filename
-            printf "Annotations\n%d errors\n" "$count"
-            while read -r line; do
-              IFS=':' read -a content <<< "$line"
-              chaine=${content[2]:1}
-              printf "%s coding style error: %s#L%s\n" "$chaine" "${content[0]}" "${content[1]}"
-              printf "%s\n" "${content[3]}"
-            done <$filename
-            exit 1
-          fi
+      uses : actions/checkout@v4
+      - run : check.sh $(pwd) $(pwd)
+      - run : |
+        if [ -s "coding-style-reports.log" ]; then
+          filename="coding-style-reports.log"
+          count=0
+          while read -r line; do
+            ((count+=1))
+          done <$filename
+          printf "Annotations\n%d errors\n" "$count"
+          while read -r line; do
+            IFS=':' read -a content <<< "$line"
+            chaine=${content[2]:1}
+            printf "%s coding style error: %s#L%s\n" "$chaine" "${content[0]}" "${content[1]}"
+            printf "%s\n" "${content[3]}"
+          done <$filename
+          exit 1
+        fi
 
   check_program_compilation:
     runs-on : ubuntu-latest
